version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3307:3306
  achat-backend:
    depends_on:
      - mysqldb
    image: khalilsr/achat:1.0.0
    restart: on-failure
    environment:
      MYSQL_ROOT PASSWORD: root_password
    ports:
      - 8082:8082
    stdin_open: true
    tty: true