version: "3.8"

services:

    mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=achatdb
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql
    
    # prometheus:
    #   image: prom/prometheus
    #   container_name: prometheus-achat-backend
    #   restart: unless-stopped
    #   volumes:
    #     - ./prometheus:/etc/prometheus // mount the local ./prometheus directory to /etc/prometheus in the container
    #     - prometheus_data:/prometheus // mount the prometheus_data volume to /prometheus in the container
    #   command:
    #     - '--config.file=/etc/prometheus/prometheus.yml' // specify the location of the prometheus configuration file
    #   links:
    #     - prom_mysql_exporter // link to the prom_mysql_exporter service
    #   ports:
    #     - 9090:9090 // expose port 9090 on the host machine

    # prom_mysql_exporter:
    #   image: prom/mysqld-exporter
    #   restart: unless-stopped
    #   links:
    #     - mysqldb // link to the mysqldb service
    #   ports:
    #     - '9104:9104' // expose port 9104 on the host machine
    #   environment:
    #     DATA_SOURCE_NAME: root:@(mysql:3306)/achatdb // specify the data source name for the exporter
    #   command: /bin/mysqld_exporter collect.binlog_size=true collect.info_schema.processlist=true // specify the command to run when starting the container

    # grafana:
    #     image: grafana/grafana
    #     container_name: grafana-achat-backend
    #     restart: unless-stopped
    #     ports:
    #       - 3000:3000 // expose port 3000 on the host machine
    #     volumes:
    #       - ./grafana:/etc/grafana/provisioning // mount the local ./grafana directory to /etc/grafana/provisioning in the container
    #       - ./grafana/dashboards:/var/lib/grafana/dashboards // mount the local ./grafana/dashboards directory to /var/lib/grafana/dashboards in the container
    #       - ./grafana/datasources:/var/lib/grafana/datasources // mount the local ./grafana/datasources directory to /var/lib/grafana/datasources in the container
    #     environment:
    #       - GF_SECURITY_ADMIN_USER=admin // set the Grafana admin username
    #       - GF_SECURITY_ADMIN_PASSWORD=thinkpad // set the Grafana admin password


    achat-backend:
        depends_on:
          - mysqldb
        image: saifdoghri7/achat:1.0.0
        restart: on-failure
        ports:
          - 8082:8082
        environment:
          SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
        }'

        stdin_open: true
        tty: true
volumes:
    db:
    prometheus_data:
