global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysqldb'
    static_configs:
      - targets: 
        - '192.168.1.222:9104'

  - job_name: 'achat-backend'
    static_configs:
      - targets:
        - '192.168.1.222:8082'
  
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - '192.168.1.222:9090'
  